# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='engine name')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('dictionary', models.TextField(default='')),
                ('sample', models.TextField(default='')),
            ],
        ),
    ]
